[package]
name = "rustos"
version = "0.1.0"
edition = "2024"
authors = ["suunj <suunj@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "rustos"
test = false
bench = false

[dependencies]


